# Generated by Django 5.2.17 on 2026-10-03 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
