# Generated by Django 5.2.17 on 2026-10-04 04:31

from django.db import migrations, models


def number_existing_categories(apps, schema_editor):
    # Keep today's order (creation order) instead of starting everyone at 0.
    Category = apps.get_model("menu", "Category")
    for position, category in enumerate(Category.objects.order_by("pk"), start=1):
        category.display_order = position
        category.save(update_fields=["display_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('display_order', 'name'), 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(number_existing_categories, migrations.RunPython.noop),
    ]
